---
title: "DARS analysis"
output: html_notebook
---

```{r setup}

#load libraries (install if you don't have them!)
library(reshape2)
library(readr) 
library(tidyverse)
library(ggplot2)
library(ggpubr)

#bring in data (pulled from REDCap)
df <- read_csv("CURAGE_DATA_2019-07-11_1042.csv") 

#set a "seed", so we can replicate our random selections
set.seed(123)

```

```{r fakeData_lists}

#make lists of hobbies, food, social, sensory that people might have - lists taken from DARS paper

#hobbies 
hobbies <- c('Concerts',
'Museums',
'Theater',
'Dance shows',
'Comedy clubs',
'Listen to music',
'Gym workout',
'Science research',
'Spinning',
'Biking',
'Martial arts',
'Running',
'Swimming',
'Yoga',
'Meditation',
'Gardening',
'Yard work',
'House repair',
'Cleaning')

#foods
foods <- c('Butter chicken',
  'Dumplings',
  'Chicken noodle soup',
  'Lasagna', 
  'Bagels', 
  'Brownies', 
  'Butter chicken', 
  'Dumplings', 
  'Chicken noodle soup', 
  'Lasagna', 
  'NY strip steak', 
  'Perogies', 
  'Sushi', 
  'Bubble tea', 
  'Coffee', 
  'Gatorade', 
  'Fruit smoothies', 
  'Margaritas', 
  'Red wine', 
  'Coca-cola', 
  'Chocolate milk', 
  'Orange juice')

#social
social <-c('Play in band',
'Act in play', 
'Going dancing',
'Going to concerts',
'House party',
'Going to plays',
'Dance classes',
'Art exhibits',
'Meet new people',
'Bowling',
'Cards',
'Chess',
'Shopping',
'Playing pool',
'Cottage trips',
'Camping',
'Karaoke',
'Play with grandkids',
'Biking',
'Going to gym')

#sensory
sensory <-c('Bread', 
'Nature', 
'Home cooked food', 
'Partners fragrance', 
'Candles', 
'Sea', 
'Coffee', 
'Flowers', 
'Hawaiian pizza', 
'Massage', 
'Sex', 
'Feel sun on skin', 
'Cuddling', 
'Back scratch', 
'Petting dog', 
'Hot bath', 
'Hugs', 
'Listening to music', 
'Comedy podcasts')

```

```{r fakeData_addingValues}

####################################
#set up our dataframe
####################################

#delete all test data (turn off when fake records have been removed from database)
df[,]=matrix(ncol=ncol(df), rep(NA, prod(dim(df))))

#initialize our dataframe
df[nrow(df)+18,] <- NA #for now, just 20 participants to play with; can change value 

#make fake subject IDs
df$record_id <- seq(1, nrow(df), by=1) #generating sequence of numbers from 1 to number of rows in df
df$record_id <- sprintf("%02d", df$record_id) #padding all values under record_id column to 2 digits
df$record_id <- paste("curage_", df$record_id, sep = "", collapse = NULL) #concatenate "curage_id" with existing 2 didgit record id's 1 - 20

#make a vector of the number of participants/rows in the df - will be useful later
record_id <- 1:nrow(df) 

#add a column with fake diagnosis (DEP, HC)
df$dars_diagnosis <- sample(c('HC', 'MDD'), size=nrow(df), replace=T)

#add a column with fake sex (M, F)
df$dars_gender <- sample(c('M', 'F'), size=nrow(df), replace=T)

#add a column with fake age (20 to 35 and 65 to 80)
df$dars_age <- sample(c(20:35, 65:80), size=nrow(df), replace=T)

########################################################################
#make lists of the variables we'll be working with!
########################################################################

#hobbies
hobbiesList_idx <-  grep("dars_hobbies_", names(df)) #list of index of these vars - exclude ratings
hobbiesRatings_idx <-  grep("dars_hobbies_ratings_", names(df)) #list of index of these vars

#foods
foodsList_idx <-  grep("dars_foods_", names(df)) #list of index of these vars - exclude ratings
foodsRatings_idx <-  grep("dars_foods_ratings_", names(df)) #list of index of these vars

#social
socialList_idx <-  grep("dars_social_", names(df)) #list of index of these vars - exclude ratings
socialRatings_idx <-  grep("dars_social_ratings_", names(df)) #list of index of these vars

#sensory
sensoryList_idx <-  grep("dars_sensory_", names(df)) #list of index of these vars - exclude ratings
sensoryRatings_idx <-  grep("dars_sensory_ratings_", names(df)) #list of index of these vars


##########################################################################
#now, let's write some functions that will help us avoid redundant code
##########################################################################

#######################
#select item from list
#######################

#for each DARS category, and each participant (row), we want a random number, between 2 and the max number of variable columns 
#note, the max number of variables is always 10, and min number is always 2, because of structure of DARS scale 
countChoice  <- sample(2:10, nrow(df), replace=T)

#write a function to make vectors of variable of interest (hobbies, food, social, sensory)
darsChoice_fn <- function(category, countChoice, index){ #takes 3 arguments
  selected <- sample(category, size=countChoice[index]) #selects the same number of the category (e.g. hobbies) as the value, per index
  selected_length <- length(selected) #stores the length of each selection
  vec <- c(selected, rep(NA, (ncol(df)-1)-selected_length)) #creates a vector of the category (e.g. hobbies) and the rest NA 
  return(vec) #return the vector
}

#######################
#select value
#######################

#random number between 1 and 5 on the Likert scale, for each participant/row in the database
countValue  <- sample(1:5, nrow(df), replace=T)

#write a function to fill in the vectors of variable of interest (hobbies, food, social, sensory) with a value
darsRating_fn <- function(category, index){ #takes 2 arguments
  values  <- sample(1:5, nrow(df), replace=T) #randomly sample values between 1 and 5 (Likert scale)
  return(values) #return the vector
}


#####################################################
#now, let's run the functions to fill in values
#####################################################


#HOBBIES 

#fill in hobbies from list
for (par in record_id) { #for each participant in our list of participants...
  vec <- darsChoice_fn(hobbies, countChoice, par) #...run the function...
  df[par, hobbiesList_idx] <- vec #...add output to the df; note, index will change if database structure changes
}

#fill in ratings
for (par in record_id) {
  vec <- darsRating_fn(hobbies, hobbiesRatings_idx)
  df[par, hobbiesRatings_idx] <- vec
}


#FOOD 
for (par in record_id) { #for each participant in our list of participants...
  vec <- darsChoice_fn(foods, countChoice, par) #...run the function...
  df[par, foodsList_idx] <- vec #...add output to the df; note, index will change if database structure changes
}

#fill in ratings
for (par in record_id) {
  vec <- darsRating_fn(foods, foodsRatings_idx)
  df[par, foodsRatings_idx] <- vec
}

#SOCIAL
for (par in record_id) { #for each participant in our list of participants...
  vec <- darsChoice_fn(social, countChoice, par) #...run the function...
  df[par, socialList_idx] <- vec #...add output to the df; note, index will change if database structure changes
}

#fill in ratings
for (par in record_id) {
  vec <- darsRating_fn(social, socialRatings_idx)
  df[par, socialRatings_idx] <- vec
}


#SENSORY
for (par in record_id) { #for each participant in our list of participants...
  vec <- darsChoice_fn(sensory, countChoice, par) #...run the function...
  df[par, sensoryList_idx] <- vec #...add output to the df; note, index will change if database structure changes
}

#fill in ratings
for (par in record_id) {
  vec <- darsRating_fn(sensory, sensoryRatings_idx)
  df[par, sensoryRatings_idx] <- vec
}
```


```{r munging}

#make a list of all the variables with the string 'ratings' in the name
ratings_vars <- grep("ratings", names(df), value=TRUE) 

#make sure that all of the 'ratings' variables are numeric (not characters)
df[, ratings_vars] <- lapply(ratings_vars, function(x) as.numeric(df[[x]]))

#now, sum across all of these columns (ignore NA)
df$dars_totalScore <- rowSums(df[, colnames(df) %in% ratings_vars], na.rm=T) #we probably shouldn't ignore NA - if we're missing a value, we do want NA, as something has gone wrong

#create new column in df for age_category (young vs old)
#http://www.talkstats.com/threads/adding-a-new-column-in-r-data-frame-with-values-conditional-on-another-column.30924/
#df$dars_age_category[df$dars_age>=20 & df$dars_age<=35]<-"young"
#df$dars_age_category[df$dars_age>=60 & df$dars_age<=80]<-"old"
df$dars_age_category <- ifelse(df$dars_age <= 35, 'young', 'old')
#^I moved this up to be with similar stuff (new variable creation, and did it in simpler way - it reads: if age is equal to or less than 35, write 'young', otherwise, write 'old')

```

```{r statistics unpaired 2 sample t test for total rating scores}

#follow the examples here: http://www.sthda.com/english/wiki/unpaired-two-samples-t-test-in-r

###############################################################
#mean dars_totalScore for MDD vs mean dars_totalScore for HC
###############################################################

#data summary
group_by(df, dars_diagnosis) %>% 
  summarise(
    count = n(),
    mean = mean(dars_totalScore , na.rm = TRUE),
    sd = sd(dars_totalScore , na.rm = TRUE)
  )

#visualize the data using boxplots!
ggboxplot(df, x = "dars_diagnosis", y = "dars_totalScore", 
          color = "dars_diagnosis", palette = c("#00AFBB", "#E7B800"),
        ylab = "dars_totalScore", xlab = "dars_diagnosis")

#check t-test assumptions: are the data normally distributed - using shapiro-wilk normality test?
with(df, shapiro.test(dars_totalScore[dars_diagnosis == "MDD"])) #not sig - so ok!
with(df, shapiro.test(dars_totalScore[dars_diagnosis == "HC"])) #not sig - so ok!

#check t-test assumptions: do the populations have similar variances?
res.ftest <- var.test(dars_totalScore ~ dars_diagnosis, data = df) #not sig - so ok!
res.ftest

#perform the t-test (decide if should be one to two sided!)
t.test(dars_totalScore ~ dars_diagnosis, data = df,
        var.equal = TRUE, alternative = "less")

#print the p-value
#p = .3516 #looks like 0.9065? But still same conclusion. It's a better idea to pull out the value from the results, with code, instead of hard coding it, in case anything changes!

#verbally interpret/ summarize
#Since p>alpha (.3516>.05), fail to reject the null hypothesis. Conclude that the mean total rating scores of MDD subjects is not less than that of HC subjects.

#it might be a nice idea to make shorter chunks for our results - so we can more easily them without scrolling down too far - but this is just a preference, and totally up to you!
```

```{r}
###############################################################
#mean dars_totalScore for females vs mean dars_totalScore for males
###############################################################

#first, let's summarize the data, so we can get a quick, intuitive feel for it
group_by(df, dars_gender) %>% 
  summarise(
    count = n(),
    mean = mean(dars_totalScore , na.rm = TRUE),
    sd = sd(dars_totalScore , na.rm = TRUE)
  )
#visualize the data using boxplots!
ggboxplot(df, x = "dars_gender", y = "dars_totalScore", 
          color = "dars_gender", palette = c("#00AFBB", "#E7B800"),
        ylab = "dars_totalScore", xlab = "dars_gender")
#check t-test assumptions: are the data normally distributed - using shapiro-wilk normality test?
with(df, shapiro.test(dars_totalScore[dars_gender == "F"]))
with(df, shapiro.test(dars_totalScore[dars_gender == "M"]))
#check t-test assumptions: do the populations have similar variances?
res.ftest <- var.test(dars_totalScore ~ dars_gender, data = df)
res.ftest
#perform the t-test (two sided!)
#will look something like `t.test(x ~ y, data = df)`, with a tilde, as our data is in a dataframe!
t.test(dars_totalScore ~ dars_gender, data = df,
        var.equal = TRUE)
#print the p-value
#p = .8968
#verbally interpret/ summarize
#Since p>alpha (.8968>.05), fail to reject the null hypothesis. Conclude that the mean total rating scores of female subjects is not significantly different from that of male subjects. 

###############################################################
#mean dars_totalScore for subjects aged 20-35 vs mean dars_totalScore for subjects aged 65-80
###############################################################

#first, let's summarize the data, so we can get a quick, intuitive feel for it
group_by(df, dars_age_category) %>% 
  summarise(
    count = n(),
    mean = mean(dars_totalScore , na.rm = TRUE),
    sd = sd(dars_totalScore , na.rm = TRUE)
  )
#visualize the data using boxplots!
ggboxplot(df, x = "dars_age_category", y = "dars_totalScore", 
          color = "dars_age_category", palette = c("#00AFBB", "#E7B800"),
        ylab = "dars_totalScore", xlab = "dars_age_category")
#check t-test assumptions: are the data normally distributed - using shapiro-wilk normality test?
with(df, shapiro.test(dars_totalScore[dars_age_category == "old"]))
with(df, shapiro.test(dars_totalScore[dars_age_category == "young"]))
#check t-test assumptions: do the populations have similar variances?
res.ftest <- var.test(dars_totalScore ~ dars_age_category, data = df)
res.ftest
#perform the t-test (two sided!)
#will look something like `t.test(x ~ y, data = df)`, with a tilde, as our data is in a dataframe!
t.test(dars_totalScore ~ dars_age_category, data = df,
        var.equal = TRUE)
#print the p-value
#p = .4087
#verbally interpret/ summarize
#Since p>alpha (.4087>.05), fail to reject the null hypothesis. Conclude that the mean total rating scores of old subjects is not significantly different from that of young subjects. 

```


```{r statistics paired 2 sample t test for total rating scores}

#creating columns containing totals for each rating category (hobbies, foods, social, sensory)
df$dars_hobbies_ratings_total <- df$dars_hobbies_ratings_01 + df$dars_hobbies_ratings_02 + df$dars_hobbies_ratings_03 + df$dars_hobbies_ratings_04

df$dars_foods_ratings_total <- df$dars_foods_ratings_01 + df$dars_foods_ratings_02 + df$dars_foods_ratings_03 + df$dars_foods_ratings_04

df$dars_social_ratings_total <- df$dars_social_ratings_01 + df$dars_social_ratings_02 + df$dars_social_ratings_03 + df$dars_social_ratings_04

df$dars_sensory_ratings_total <- df$dars_sensory_ratings_01 + df$dars_sensory_ratings_02 + df$dars_sensory_ratings_03 + df$dars_sensory_ratings_04

###########################################################################################
#HELP
#http://www.sthda.com/english/wiki/paired-samples-t-test-in-r

#Within each group of subjects (MDD, HC, female, male, young, old), we are trying to compare the mean total rating score for hobbies to mean total rating score for foods; 

#This analysis is going to give rise to a lot of tests! We should make sure that this analysis is well-motivated theoretically, and we will have to consider controlling for multiple comparisons. I am not sure that this would be a t-test; as what we are doing is looking at the distribution of data within a narrow group (e.g., MDD, female, young, compared on hobbies, food, social, etc). Also, for our synthetic data here, and possibly in our real data, we will h we will have very small sample sizes if we 'slice' the data in this way. :)

#I think a better way to approach this at this would be to visualize the distribution of the data for each group, and follow up with a statistical test - I believe an ANOVA followed up by t-tests if significant. 

#First, let's take a smaller subset of the dataframe so easier to think about
df.totals <- df[, c("record_id", "dars_diagnosis",  "dars_gender", "dars_age_category",
  "dars_hobbies_ratings_total", "dars_foods_ratings_total", "dars_social_ratings_total", "dars_sensory_ratings_total")]

#Now, we 'melt' the dataframe, to get it in the right 'shape' (take a look - we have one row for each participant for each score)
df.totals <- melt(df.totals, id.vars=c("record_id", "dars_diagnosis",  "dars_gender", "dars_age_category"))

#plot
ggplot(data = df.totals, aes(x=value)) + geom_density(aes(fill=dars_diagnosis), alpha = 0.4) + facet_wrap(variable ~ dars_age_category) #we cat add a third 'facet' of dars_gender, but we don't have enough data at the moment in these very small groups!


#the mean total rating score for hobbies to mean total rating score for social; 
#the mean total rating score for hobbies to mean total rating score for sensory; 
#the mean total rating score for foods to mean total rating score for social; 
#the mean total rating score for foods to mean total rating score for sensory; 
#the mean total rating score for social to mean total rating score for sensory

#I do not know how to apply the paired two sample t test process as outlned in the website above to our data - because out data frame is organized differently (their data frame only contains data from the one group of subjects in question while ours contains multiple - MDD, HC, F, M, young, old; 
#also, in the website, the two categories being compared (in their case, before and after) are placed in the same column while the categories we're comparing are placed in different columns - (dars_hobbies_ratings_total, dars_foods_ratings_total, social_ratings_total, dars_sensory_ratings_total))

###########################################################################################

```



```{r extra_code}
 
df$dars_hobbies_ratings_01 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_hobbies_ratings_01"
df$dars_hobbies_ratings_02 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_hobbies_ratings_02"
df$dars_hobbies_ratings_03 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_hobbies_ratings_03"
df$dars_hobbies_ratings_04 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_hobbies_ratings_04"

df$dars_foods_ratings_01 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_foods_ratings_01"
df$dars_foods_ratings_02 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_foods_ratings_02"
df$dars_foods_ratings_03 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_foods_ratings_03"
df$dars_foods_ratings_04 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_foods_ratings_04"

df$dars_social_ratings_01 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_social_ratings_01"
df$dars_social_ratings_02 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_social_ratings_02"
df$dars_social_ratings_03 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_social_ratings_03"
df$dars_social_ratings_04 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_social_ratings_04"

df$dars_sensory_ratings_01 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_sensory_ratings_01"
df$dars_sensory_ratings_02 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_sensory_ratings_02"
df$dars_sensory_ratings_03 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_sensory_ratings_03"
df$dars_sensory_ratings_04 <-sample(x = 1:5, size = 20, replace = TRUE)#randomly inputting numbers from likert scale (wherein 1 = "not at all" and 5 = "always") into "dars_sensory_ratings_04"


```

